### ISSUE TITLE
[META] What do we want to see in this package?

### ISSUE THREAD

**Issue by Batalex** [pyOpenSci/pyosPackage#3]
Here are a few suggestions, doubling as a tracker for the implementation of said features.

# Tracker

## Code structure & content

- [ ] `src` versus flat layout, see #2 
- [ ] File format configuration (e.g. `.editorconfig`)
- [ ] Dependencies management
- [ ] .gitignore

## Documentation

- [ ] Badges
- [ ] "Written" documentation
- [ ] API reference
- [ ] Publishing

## Code quality

- [ ] Formatter
- [ ] Linter(s), see #1 
- [ ] Type checker, see #1 
- [ ] Tests, see #1

## Collaboration

- [ ] Licensing
- [ ] CoC
- [ ] Contributing guide

## Packaging
- [ ] Versionning
- [ ] Building
- [ ] Publishing

## Automation

- [ ] Setting up CI for as many items as possible, see #1 
- [ ] Running everything locally

# Implementations

Based on the [pyOpenSci packaging guide](https://github.com/pyOpenSci/pyosPackage/issues/new), here are a few implementation suggestoins

## Code structure & content

- [ ] `src` versus flat layout: **src** 
- [ ] File format configuration (e.g. `.editorconfig`): 
```
root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
trim_trailing_whitespace = true

[*.py]
indent_style = space
indent_size = 4

[*.md]
trim_trailing_whitespace = false
```
- [ ] Dependencies management: **PDM**
- [ ] .gitignore: [gitignore.io for Python](https://www.toptal.com/developers/gitignore/api/python)
## Documentation

- [ ] Badges
- [ ] "Written" documentation: **Sphinx**
- [ ] API reference: **apidoc**
- [ ] Publishing: **GH pages**

## Code quality

- [ ] Formatter: **Black**
- [ ] Linter(s): **Ruff** 👼 
- [ ] Type checker: **mypy**
- [ ] Tests: **pytest, coverage.py**

## Collaboration

- [ ] Licensing: **MIT, BSD3?**
- [ ] CoC
- [ ] Contributing guide

## Packaging

- [ ] Versionning
- [ ] Building: **PDM**
- [ ] Publishing: **PyPI, conda-forge, both?**

## Automation

- [ ] Setting up CI: **GH actions**
- [ ] Running everything locally: **tox, nox, PDM?**

Feel free to comment / change items 🐈‍⬛

**Comment by lwasser** [comment]
Ok i'm finally carving out time to work on this with our workshop coming up!! thank you for this super detailed issue @Batalex - i'm sorry it has taken me so long to get to it! i'm going to work on some of this - this week!! 

 i'll open pr's for review

**Comment by lwasser** [comment]
@all-contributors please add @Batalex for review
